#define PJ_CONFIG_ANDROID 1
#define PJMEDIA_HAS_G729_CODEC 1
#define PJMEDIA_HAS_G7221_CODEC 1

#include <pj/config_site_sample.h>

#define PJ_CONFIG_ANDROID 1
#define PJMEDIA_HAS_G729_CODEC 1
#define PJMEDIA_HAS_G7221_CODEC 1

#define PJMEDIA_HAS_VIDEO 0
#define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI 1
#define PJMEDIA_AUDIO_DEV_HAS_OPENSL 0
//#define PJSIP_AUTH_AUTO_SEND_NEXT 0
#define PJSIP_AUTH_AUTO_SEND_NEXT 1 //Try for Asterisk
//#define PJMEDIA_HAS_SPEEX_AEC 0
#define PJMEDIA_HAS_SPEEX_AEC 1
#define PJMEDIA_SPEEX_AEC_USE_AGC 1

#define PJMEDIA_HAS_WEBRTC_AEC 1
#define PJMEDIA_WEBRTC_AEC_USE_MOBILE 1


#define PJSIP_AUTH_HEADER_CACHING 1 //Try for Asterisk


#define PJMEDIA_SPEEX_AEC_USE_DENOISE 0 //Remove adds

#define PJMEDIA_A_R 1
